version: '3.8'

services:
  api:
    build: './API'
    environment:
      PORT: 8000
      PGHOST: db
      PGDATABASE: library
      PGPORT: 5432
      PGUSER: student
      PGPASSWORD: student
      AMQPURL: amqp://rabbitmq
    ports:
      - 9000:8000
    restart: on-failure
    depends_on:
      - rabbitmq

  procesator:
    build: './Procesator'
    environment:
      PORT: 8000
      PGHOST: db
      PGDATABASE: library
      PGPORT: 5432
      PGUSER: student
      PGPASSWORD: student
      AMQPURL: amqp://rabbitmq
    restart: on-failure
    depends_on:
      - rabbitmq

  db: 
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: library
    volumes:
      - ./Database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  rabbitmq:
    image: rabbitmq:3

    