version: '3.8'

services:
  api:
    build: './API'
    environment:
      PORT: 8000
      PGHOST: db
      PGDATABASE: log
      PGPORT: 5432
      PGUSER: ryanair
      PGPASSWORD: 737max
      AMQPURL: amqp://rabbitmq
    ports:
      - 9000:8000
    restart: on-failure
    depends_on:
      - rabbitmq

  procesator:
    build: './Procesator'
    environment:
      PORT: 8000
      PGHOST: db
      PGDATABASE: log
      PGPORT: 5432
      PGUSER: ryanair
      PGPASSWORD: 737max
      AMQPURL: amqp://rabbitmq
    restart: on-failure
    depends_on:
      - rabbitmq

  db: 
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ryanair
      POSTGRES_PASSWORD: 737max
      POSTGRES_DB: log
    volumes:
      - ./Database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  rabbitmq:
    image: rabbitmq:3

    