apiVersion: v1
kind: Pod
metadata:
  labels:
    run: api
  name: api
spec:
  containers:
  - image: mobylab/cc-laborator5-api
    name: api
    envFrom:
      - secretRef:
          name: proc-secret
    env:
    - name: PORT
      value: "8000"
    - name: PGHOST
      value: db-cluster-ip-service
    - name: PGPORT
      value: "5432"
    - name: AMQPURL
      value: amqp://rabbitmq-cluster-ip-service
  dnsPolicy: ClusterFirst
  restartPolicy: Always
