apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: db
  name: db
spec:
  containers:
  - image: mobylab/cc-laborator5-db
    name: db
    envFrom:
      - secretRef:
          name: db-secret
    volumeMounts:
      - mountPath: /var/lib/postgresql/data
        name: mypd
 
 
  volumes:
  - name: mypd
    persistentVolumeClaim:
      claimName: dbpvc

