apiVersion: v1
kind: Pod
metadata:
  labels:
    run: procesator
  name: procesator
spec:
  containers:
  - image: mobylab/cc-laborator5-proc
    name: procesator
    envFrom:
      - secretRef:
          name: proc-secret
    env:
    - name: PORT
      value: "8000"
    - name: PGHOST
      value: db-cluster-ip-service
    - name: PGPORT
      value: "5432"
    - name: AMQPURL
      value: amqp://rabbitmq-cluster-ip-service
  dnsPolicy: ClusterFirst
  restartPolicy: Always
